language: node_js
node_js:
- '0.12'
env:
  global:
    secure: "cFJZm9sNr/dNqG4ZA2wqt2FefO4nZs7S0yst4rLfwio9lJX314pz+fzbl/v/S+j+t/2aniGMmVBCusfoV2jEDam0s4tmDEX+tGQp5hFpA1hnTRnscPGRuvio9/Wm3AQ/5HViVQlc3dnjYUhOwd6s2UthvpjTU5op5lKi++4di/eD0mbcVlleOcmP5syPioQEvrYYncUHG4++WzyQzTX3zPeHqOeTFFr1+TeRmjPzg8m8jDjLOWwdT1qu8MloFnY7wAuokrjL9T1Scv3IVmutKJvODT4yLMQLDHtfcE5juz0EGhlKOgYVUrqGZ0azAQLDYryQdsG3ohnk44u5VY67dmI89ItDtkzty/kk/N+B9J5dGe2oGmUr4XSP16HflntC2NNB4b6L/veOVfgqecmqrp9gDK277gcqsNTSFcqAYKS+2TEsrrvpmAzg3JvTtz+wEP+ehVTmAccTKKca0D88pTwSkwovzRajw1WzDO9Ys0hZHuWIaVBZdP1cGN6EcuqChO6RavXNfPTzsfjJmHs4I++d7AX/uVESdDZzDZ72VmXZB+AfBfAU/HYpcuEJ+HqVnGgQ9r6ZcTahyCk0I1l2w9x5y17p1XaKCwZV/YTHeIl67xv7uQ9FXap9JNDIteuUlIRF7QUEeHctNzEs4oZPi7eXcCWXTgpNL0CwRJ03B2M="
before_script:
  - npm install -g bower
  - bower install
after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
  - 'curl "http://technical.viadeo-playground.com/deploy/update?secret_key=$PASSWORD&site=cloudbudget_angularjs"'